{{- if index .Values.telegraf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "firehose.fullname" . }}-telegraf
  namespace: {{ .Release.Namespace }}
  labels: {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
data:
  telegraf.conf: |+
{{- include "firehose.telegraf.conf" . | indent 4}}
{{- end }}
