apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "firehose.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
data:
  {{- toYaml .Values.firehose.config | nindent 2 }}
