{{- if .Values.autoscaler.enabled and .Values.autoscaler.type == "keda"}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels: {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
    scaledobject.keda.sh/name: {{ include "firehose.fullname" . }}
  name: {{ include "firehose.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  fallback:
    {{- if .Values.autoscaler.keda.fallback }}
    {{- toYaml .Values.autoscaler.keda.fallback | nindent 4 }}
    {{- end }}
  advanced:
    horizontalPodAutoscalerConfig:
      {{- if .Values.autoscaler.keda.advanced.horizontalPodAutoscalerConfig }}
      {{- toYaml .Values.autoscaler.keda.advanced.horizontalPodAutoscalerConfig | nindent 6 }}
      {{- end }}
      name: {{ include "firehose.fullname" . }}
  {{- if .Values.autoscaler.keda.maxReplicaCount }}
  maxReplicaCount: {{ .Values.autoscaler.keda.maxReplicaCount }}
  {{- end }}
  {{- if .Values.autoscaler.keda.minReplicaCount }}
  minReplicaCount: {{ .Values.autoscaler.keda.minReplicaCount }}
  {{- end }}
  {{- if .Values.autoscaler.keda.pollingInterval }}
  pollingInterval: {{ .Values.autoscaler.keda.pollingInterval }}
  {{- end }}
  {{- if .Values.autoscaler.keda.cooldownPeriod }}
  cooldownPeriod: {{ .Values.autoscaler.keda.cooldownPeriod }}
  {{- end }}
  scaleTargetRef:
    name: {{ include "firehose.fullname" . }}
  triggers:
    {{- range $trigger := .Values.autoscaler.keda.triggers }}
    - type: {{ $trigger.type }}
      metadata:
        {{- range $key, $value := $trigger.metadata }}
        {{ $key }}: {{ $value }}
        {{- end }}
      {{- if $trigger.authenticationRef }}
      authenticationRef:
        name: {{ $trigger.authenticationRef.name | default (include "firehose.fullname" .) }}
      {{- end }}
    {{- end }}
{{- end -}}