{{- if .Values.autoscaler.enabled and .Values.autoscaler.type == "keda"}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels: {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
    scaledobject.keda.sh/name: {{ include "firehose.fullname" . }}
  name: {{ include "firehose.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- if len .Values.autoscaler.keda.annotations > 0 }}
  annotations:
    {{- range $key, $value := .Values.autoscaler.keda.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.autoscaler.keda.fallback.behavior }}
  fallback:
    behavior: {{ .Values.autoscaler.keda.fallback.behavior }}
    failureThreshold: {{ .Values.autoscaler.keda.fallback.failureThreshold  }}
    replicas: {{ .Values.autoscaler.keda.fallback.replicas }}
  {{- end }}
  advanced:
    {{- if .Values.autoscaler.keda.restoreToOriginalReplicaCount }}
    restoreToOriginalReplicaCount: {{ .Values.autoscaler.keda.restoreToOriginalReplicaCount }}
    {{- end }}
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          policies:
            {{- range $policy := .Values.autoscaler.keda.hpa.scaleUp.policies }}
            - type: {{ $policy.type }}
              value: {{ $policy.value }}
              periodSeconds: {{ $policy.periodSeconds | default 60 }}
            {{- end }}
          stabilizationWindowSeconds: {{ .Values.autoscaler.keda.hpa.scaleUp.stabilizationWindowSeconds | default 60 }}
          tolerance: {{ .Values.autoscaler.keda.hpa.scaleUp.tolerance | default 0 }}
        scaleDown:
          policies:
            {{- range $policy := .Values.autoscaler.keda.hpa.scaleDown.policies }}
            - type: {{ $policy.type }}
              value: {{ $policy.value }}
              periodSeconds: {{ $policy.periodSeconds | default 60 }}
            {{- end }}
          stabilizationWindowSeconds: {{ .Values.autoscaler.keda.hpa.scaleDown.stabilizationWindowSeconds | default 300 }}
          tolerance: {{ .Values.autoscaler.keda.hpa.scaleDown.tolerance | default 0 }}
      name: {{ include "firehose.fullname" . }}
  {{- if .Values.autoscaler.keda.maxReplicaCount }}
  maxReplicaCount: {{ .Values.autoscaler.keda.maxReplicaCount }}
  {{- end }}
  {{- if .Values.autoscaler.keda.minReplicaCount }}
  minReplicaCount: {{ .Values.autoscaler.keda.minReplicaCount }}
  {{- end }}
  {{- if .Values.autoscaler.keda.pollingInterval }}
  pollingInterval: {{ .Values.autoscaler.keda.pollingInterval }}
  {{- end }}
  {{- if .Values.autoscaler.keda.cooldownPeriod }}
  cooldownPeriod: {{ .Values.autoscaler.keda.cooldownPeriod }}
  {{- end }}
  scaleTargetRef:
    name: {{ include "firehose.fullname" . }}
  triggers:
    {{- range $trigger := .Values.autoscaler.keda.triggers }}
    - type: {{ $trigger.type }}
      metadata:
        {{- range $key, $value := $trigger.metadata }}
        {{ $key }}: {{ $value }}
        {{- end }}
      {{- if $trigger.authenticationRef.name != "" }}
      authenticationRef:
        name: {{ $trigger.authenticationRef.name }}
        kind: {{ $trigger.authenticationRef.kind | default "ScaledObject" }}
      {{- end }}
    {{- end }}
{{- end -}}