apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firehose.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}

stringData:
  {{- omit .Values.secrets "FIREHOSE_SINK_BLOB_GCS_CREDENTIAL_NAME" "FIREHOSE_SINK_BLOB_GCS_CREDENTIAL_PATH" "FIREHOSE_DLQ_GCS_CREDENTIAL_NAME" "FIREHOSE_DLQ_GCS_CREDENTIAL_PATH" "FIREHOSE_SINK_BIGQUERY_CREDENTIAL_NAME" "FIREHOSE_SINK_BIGQUERY_CREDENTIAL_PATH" | toYaml | nindent 2 }}