apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firehose.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}

stringData:
  {{- toYaml .Values.envSecrets  | nindent 2 }}
