apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firehose.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels: {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
stringData:
  {{- toYaml .Values.envSecrets  | nindent 2 }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firehose.fullname" . }}-m-secret
  namespace: {{ .Release.Namespace }}
  labels: {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
data:
  {{- range $_, $mountSecret := .Values.mountSecrets }}
    {{$mountSecret.key }}: {{ $mountSecret.value }}
  {{- end }}
