apiVersion: v2
name: compass
description: A Helm chart for running Compass in Kubernetes
type: application
version: 0.3.0
appVersion: "0.6.5"
dependencies:
  - name: app
    version: "0.7.0"
    repository: "https://goto.github.io/charts/"
