apiVersion: v2
name: compass
description: A Helm chart for running Compass in Kubernetes
type: application
version: 0.2.2
appVersion: "0.5.12"
dependencies:
  - name: app
    version: "0.5.12"
    repository: "https://goto.github.io/charts/"
