app:
  image:
    repository: gotocompany/compass
    pullPolicy: Always
    tag: "0.9.1"
  container:
    command:
      - compass
    args:
      - server
      - start
    livenessProbe:
      httpGet:
        path: /ping
        port: tcp
    readinessProbe:
      httpGet:
        path: /ping
        port: tcp

  migration:
    enabled: true
    command:
      - compass
    args:
      - server
      - migrate

  service:
    annotations: {}

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: contour
    hosts:
      - host: compass.example.com
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                # name: backend_01
                port:
                  number: 80

  config:
    COMPASS_SERVICE_PORT: 8080
    COMPASS_SERVICE_GRPC_PORT: 8081
    # COMPASS_SERVICE_HOST: 0.0.0.0
    # COMPASS_STATSD_ENABLED: false
    # COMPASS_STATSD_PREFIX: compass
    # COMPASS_LOG_LEVEL: info
    # COMPASS_TELEMETRY_APP_NAME: "compass"
    # COMPASS_TELEMETRY_NEWRELIC_ENABLED: false
    # COMPASS_TELEMETRY_OPEN_TELEMETRY_ENABLED: false
    # COMPASS_TELEMETRY_OPEN_TELEMETRY_COLLECTOR_ADDR: "127.0.0.1:4317"
    # COMPASS_TELEMETRY_OPEN_TELEMETRY_PERIODIC_READ_INTERVAL: 5s
    # COMPASS_TELEMETRY_OPEN_TELEMETRY_TRACE_SAMPLE_PROBABILITY: 0.1

  secretConfig: {}
    # COMPASS_ELASTICSEARCH_BROKERS: ~
    # COMPASS_STATSD_ADDRESS: ~
    # COMPASS_TELEMETRY_NEWRELIC_LICENSEKEY: ~
    # COMPASS_DB_HOST: ~
    # COMPASS_DB_PORT: 5432
    # COMPASS_DB_NAME: ~
    # COMPASS_DB_USER: ~
    # COMPASS_DB_PASSWORD: ~
    # COMPASS_DB_SSLMODE: disable

cron:
  enabled: true
  jobs:
    - name: cleanup
      schedule: "0 5 * * *" # Every day at 5 AM
      command:
        - compass
        - cleanup
        - start
