apiVersion: v2
name: entropy
description: A Helm chart for Kubernetes
type: application
version: 0.1.4
appVersion: 0.1.0
dependencies:
- name: app
  version: "0.5.6"
  repository: "https://goto.github.io/charts/"
