apiVersion: v2
name: entropy
description: A Helm chart for Kubernetes
type: application
version: 0.1.7
appVersion: 0.1.2
dependencies:
- name: app
  version: "0.5.12"
  repository: "https://goto.github.io/charts/"
  alias: app
  condition: app.enabled
- name: workers
  version: "0.5.12"
  repository: "https://goto.github.io/charts/"
  alias: workers
  condition: workers.enabled