apiVersion: v2
name: entropy
description: A Helm chart for Kubernetes
type: application
version: 0.1.8
appVersion: 0.1.26
dependencies:
- name: app
  version: "0.6.0"
  repository: "https://goto.github.io/charts/"
  alias: app
  condition: app.enabled
- name: app
  version: "0.6.0"
  repository: "https://goto.github.io/charts/"
  alias: worker
  condition: worker.enabled