apiVersion: v2
name: dex
description: A Helm chart for Kubernetes
type: application
version: 0.1.2
appVersion: 0.1.1
dependencies:
- name: app
  version: "0.5.6"
  repository: "https://goto.github.io/charts/"
