schedule: "0 1 * * *"
concurrencyPolicy: "Forbid"
image:
  # [required] repository where meteor Docker image is available
  repository: gotocompany/meteor
  tag: "0.8.0"
  pullPolicy: IfNotPresent
labels: {"application":"meteor"}

config: {}
secretConfig: {}
# pass in secret names to be mounted to cronjob
ssl_secrets: []

jobDeadlineSeconds: 14400

resources:
  {}
  # -- We usually recommend not to specify default resources and to leave this as a conscious
  # -- choice for the user. This also increases chances charts run on environments with little
  # -- resources, such as Minikube. If you do want to specify resources, uncomment the following
  # -- lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # -- limits:
  # --   cpu: 100m
  # --   memory: 128Mi
  # -- requests:
  # --   cpu: 100m
  # --   memory: 128Mi


# sample recipe usage
# recipes:
#   sample-recipe.yaml: |-
#     name: sample-recipe
#     source:
#       type: sample
#       config:
#         foo: "bar"
#     sinks:
#       - name: console
telegraf:
  enabled: false
  image: telegraf:1.19.3-alpine
  config: ~ # telegraf config
  containerPort: 8125
  protocol: UDP
  args:
  command:
    - telegraf

otelcollector:
  enabled: false
  image: otel/opentelemetry-collector-contrib:0.79.0
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
    exporters:
      logging:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]

serviceAccount:
  name: ""
  tokenProjection:
    enabled: false
    mountPath: "/var/run/secrets/tokens"
    expirationSeconds: 600
    audience: ""
