apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.fullname" . }}-rollback-job
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command:
            {{- toYaml .Values.rollback.command | nindent 12 }}
          args:
            {{- toYaml .Values.rollback.args | nindent 12 }}
          envFrom:
            - configMapRef:
                name: "{{ include "app.fullname" . }}"
          {{- if .Values.secretConfig }}      
            - secretRef:
                name: "{{ template "app.fullname" . }}-secret"
          {{- end }}
          volumeMounts:
            - mountPath: /etc/optimus
              name: configuration-volume
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
