app:

  ## Value to fully override guardian.name template
  nameOverride: ""
  ## Value to fully override guardian.fullname template
  fullnameOverride: ""

  image:
    repository: gotocompany/guardian
    pullPolicy: Always
    tag: latest
  container:
    args:
      - server
      - start
    livenessProbe:
      httpGet:
        path: /ping
        port: tcp
    readinessProbe:
      httpGet:
        path: /ping
        port: tcp

  migration:
    enabled: true
    args:
      - server
      - migrate

  service:
    annotations:
      projectcontour.io/upstream-protocol.h2c: tcp

  cron:
    enabled: true
    jobs:
      - name: "fetch-resources"
        schedule: "0 */2 * * *"
        restartPolicy: Never
        command: []
        args:
          - job
          - run
          - fetch_resources
      - name: "expiring-grant-notification"
        schedule: "0 9 * * *"
        restartPolicy: Never
        command: []
        args:
          - job
          - run
          - expiring_grant_notification
      - name: "revoke-expired-grants"
        schedule: "*/20 * * * *"
        restartPolicy: Never
        command: []
        args:
          - job
          - run
          - revoke_expired_grants
      - name: "inactive-revocation"
        schedule: "0 7 * * *"
        restartPolicy: Never
        command: []
        args:
          - job
          - run
          - revoke_grants_by_user_criteria
      - name: "dormancy-check"
        schedule: "0 8 * * *"
        restartPolicy: Never
        command: []
        args:
          - job
          - run
          - grant_dormancy_check

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: contour
    hosts:
      - host: guardian.example.com
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                # name: backend_01
                port:
                  number: 80

  config:
    LOG_LEVEL: info
    AUTHENTICATED_USER_HEADER_KEY: x-authenticated-user-email
    NOTIFIER_PROVIDER: slack
    JOBS_FETCH_RESOURCES_ENABLED: false
    JOBS_FETCH_RESOURCES_INTERVAL: "0 */2 * * *"
    JOBS_REVOKE_EXPIRED_ACCESS_ENABLED: false
    JOBS_REVOKE_EXPIRED_ACCESS_INTERVAL: "*/20 * * * *"
    JOBS_EXPIRING_ACCESS_NOTIFICATION_ENABLED: false
    JOBS_EXPIRING_ACCESS_NOTIFICATION_INTERVAL: "0 9 * * *"
    JOBS_REVOKE_GRANTS_BY_USER_CRITERIA_CONFIG: '{"dry_run":true}'
    JOBS_GRANT_DORMANCY_CHECK_CONFIG: '{"dry_run":true}'


  secretConfig:
    ENCRYPTION_SECRET_KEY:
    NOTIFIER_ACCESS_TOKEN:
    DB_HOST: localhost
    DB_PORT:
    DB_NAME: guardian
    DB_USER: guardian
    DB_PASSWORD:
