{{- if .Values.metabase.secretConfig -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "metabase.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.labels }}
{{ toYaml .Values.labels | trim | indent 4 }}
    {{- end }}
type: Opaque
data:
  {{- if .Values.metabase.secretConfig.newRelicAppName }}
  newRelicAppName: {{ .Values.metabase.secretConfig.newRelicAppName | b64enc | quote }}
  {{- end }}
  {{- if .Values.metabase.secretConfig.newRelicLicenseKey }}
  newRelicLicenseKey: {{ .Values.metabase.secretConfig.newRelicLicenseKey | b64enc | quote }}
  {{- end }}
{{- end }}

---
{{- if and (ne (.Values.metabase.database.type | lower) "h2") (not .Values.metabase.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "metabase.fullname" . }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.labels }}
{{ toYaml .Values.labels | trim | indent 4 }}
    {{- end }}
type: Opaque
data:
  {{- if .Values.metabase.database.encryptionKey }}
  encryptionKey: {{ .Values.metabase.database.encryptionKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.metabase.database.connectionURI }}
  connectionURI: {{ .Values.metabase.database.connectionURI | b64enc | quote }}
  {{- else }}
  username: {{ .Values.metabase.database.username | b64enc | quote }}
  password: {{ .Values.metabase.database.password | b64enc | quote }}
  {{- end }}
{{- end }}

---
{{- if .Values.metabase.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "metabase.fullname" . }}-ssl
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.labels }}
{{ toYaml .Values.labels | trim | indent 4 }}
    {{- end }}
type: Opaque
data:
  keystore: {{ .Values.metabase.ssl.keystore | b64enc | quote }}
  password: {{ .Values.metabase.ssl.keyStorePassword | b64enc | quote }}
{{- end }}
