replicaCount: 1

image:
  repository: public.ecr.aws/gravitational/tbot-distroless
  tag: 16.5.13
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: "tbot-sa"
  role:
    enabled: true
    name: tbot-secrets-admins

podAnnotations: {}
podLabels: {}

resources: {}

initContainers: {}

container:
  enabled: true
  command: []
  args: []
  ports:
    - name: tcp
      containerPort: 8080
      protocol: TCP
  livenessProbe:
    httpGet:
      path: /
      port: tcp
  readinessProbe:
    httpGet:
      path: /
      port: tcp
  volumeMounts:
  - name: join-sa-token
    mountPath: /var/run/secrets/tokens


volumes:
  - name: join-sa-token
    projected:
      sources:
        - serviceAccountToken:
            path: join-sa-token
            expirationSeconds: 600
            audience: auth-server

config: {}

secretConfig: {}

telegraf:
  enabled: false
  image: telegraf:1.19.3-alpine
  config: ~
  containerPort: 8125
  protocol: UDP
  args:
  command:
    - telegraf

otelcollector:
  enabled: false
  image: otel/opentelemetry-collector-contrib:0.89.0
  useEnvFromConfig: false
  readinessProbe:
    initialDelaySeconds: 15
    periodSeconds: 5
  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 5
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
    exporters:
      logging:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]

podLabels: {}

iap:
  enabled: false
  image: gojektech/iap-auth:0.1.0-99f7459df4481772d30176e3b39b3857cd538745
  containerPort: 8989
  refreshTimeSeconds: 3590s
  serviceAccountMountPath: /etc/iap_auth
  serviceAccountFileName: sa.json
  serviceAccountSecret: iap-credentials-secret
  logLevel: error
  readinessProbe:
    initialDelaySeconds: 0
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 0
    timeoutSeconds: 5
