# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  role:
    enabled: true
    name: tbot-secrets-admins

podAnnotations: {}
podLabels: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

config: {}

secretConfig:
  {}
  # -- Example: database connection details can go under secret config
  # DB_HOST: localhost
  # DB_NAME: app
  # DB_USER: ""
  # DB_PASSWORD: ""
  # DB_PORT: 5432

telegraf:
  enabled: false
  image: telegraf:1.19.3-alpine
  config: ~ # telegraf config
  containerPort: 8125
  protocol: UDP
  args:
  command:
    - telegraf

otelcollector:
  enabled: false
  image: otel/opentelemetry-collector-contrib:0.89.0
  useEnvFromConfig: false
  readinessProbe:
    initialDelaySeconds: 15
    periodSeconds: 5
  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 5
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
    exporters:
      logging:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]

podLabels: {}

iap:
  enabled: false
  image: gojektech/iap-auth:0.1.0-99f7459df4481772d30176e3b39b3857cd538745
  containerPort: 8989
  refreshTimeSeconds: 3590s
  serviceAccountMountPath: /etc/iap_auth
  serviceAccountFileName: sa.json
  serviceAccountSecret: iap-credentials-secret
  logLevel: error
  readinessProbe:
    initialDelaySeconds: 0
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 0
    timeoutSeconds: 5
