{{- if .Values.cron.enabled }}
{{- $fullName := include "app.fullname" . -}}
{{- $appLabels := include "app.labels" . -}}
{{- $appSelectorLabels := include "app.selectorLabels" . -}}
{{- $podLabels := .Values.podLabels }}
{{- range $i, $job := .Values.cron.jobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ $fullName | trunc 24 }}-{{ $i }}-{{ $job.name | trunc 24}}"
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- $appLabels | nindent 4 }}
spec:
  schedule: {{ $job.schedule | quote }}
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        metadata:
          labels:
            {{- $appSelectorLabels | nindent 12 }}
            {{- with $podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          {{- if $job.initContainers }}
          initContainers:
            {{- range $initContainer := $job.initContainers }}
            - {{- toYaml $initContainer | nindent 14 }}
            {{- end }}
          {{- end }}
          containers:
            - name: {{ $job.name }}
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              command:
              {{- toYaml $job.command | nindent 16 }}
              args:
              {{- toYaml $job.args | nindent 16 }}
              envFrom:
                - configMapRef:
                    name: {{ $fullName }}
                - secretRef:
                    name: {{ $fullName }}-secret
              {{- if $job.volumeMounts }}
              volumeMounts:
                {{- toYaml $job.volumeMounts | nindent 16 }}
              {{- end }}
          restartPolicy: {{ $job.restartPolicy }}
          {{- if $job.volumes }}
          volumes:
            {{- range $volume := $job.volumes }}
            - {{- toYaml $volume | nindent 14 }}
            {{- end }}
          {{- end }}
---
{{- end -}}
{{- end -}}