{{- if .Values.otelcollector.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}-otelcollector
  namespace: "{{ include "app.namespace" . }}"
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{ .Values.otelcollector.config | indent 4 }}
{{- end }}
