{{- if .Values.container.enabled }}
{{- $fullName := include "app.fullname" . -}}
{{- $labels := include "app.labels" . -}}
{{- $selectorLabels := include "app.selectorLabels" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- $labels | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $port := .Values.service.ports }}
    - port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      protocol: {{ $port.protocol }}
      name: {{ $port.name }}
    {{- end }}
  selector:
    {{- $selectorLabels | nindent 4 }}
{{- if .Values.service.additionalService }}
  {{- range .Values.service.additionalService }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" $fullName .name }}
  labels:
    {{- $labels | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .type }}
  ports:
    {{- range $port := .ports }}
    - port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      protocol: {{ $port.protocol }}
      name: {{ $port.name }}
    {{- end }}
  selector:
    {{- $selectorLabels | nindent 4 }}
  {{- end }}
{{- end }}
{{- end -}}